spring:
  application:
    name: duelingo-backend

  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true

app:
  content:
    bootstrap-enabled: ${CONTENT_BOOTSTRAP_ENABLED:true}
